version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    image: ninvit/ninfinances:backend
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb+srv://ninvit:6a9p91SE6aO7RN8E@cluster0.bezll.mongodb.net/ninfinances?retryWrites=true&w=majority&appName=Cluster0"
      JWT_SECRET: "your_jwt_secret_key"
      PORT: "3000"
      NODE_ENV: "production"
    volumes:
      - ./:/app
      - /app/node_modules

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    image: ninvit/ninfinances:frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongodb_data: 