spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://ninvit:6a9p91SE6aO7RN8E@cluster0.bezll.mongodb.net/ninfinances}
  security:
    jwt:
      secret: ${JWT_SECRET:minhaChaveSecretaMuitoSeguraComMaisDe256Bits12345678901234567890123456789012345678901234567890}
      expiration: 86400000 # 24 hours
  web:
    resources:
      static-locations: classpath:/static/
      cache-period: 3600

server:
  port: ${PORT:8080}
  compression:
    enabled: true

cors:
  allowed-origins: ${ALLOWED_ORIGINS:https://ninfinances-415b08c409ff.herokuapp.com,http://localhost:3000,http://localhost:8080,http://localhost:8081,http://localhost:8082}

logging:
  level:
    com.ninfinances: DEBUG
    org.springframework.security: INFO 